### ISSUE TITLE
Fuzzy search for getting email?

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#153]
Currently misspelled names return no results and the labels table is no longer being used.

The fuzzywuzzy package may have some methods to get better results when names are misspelled (ex. "Etan Markus")

**Comment by abrahammurciano** [comment]
Currently the database handles searches. If we want to use fuzzy-wuzzy we would need to pull all the data from the database, probably at startup, then keep our loaded copy synced whenever stuff is added/updated/deleted. Doable tho. I wonder however if there's a fuzzy search equivalent available in SQL
