### ISSUE TITLE
Events can get skipped since the list embedder limits the description to 2048 characters

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#154]
The calendar embedder limits descriptions to 2048 characters, so any events over that limit do not get shown even if they belong on that page.

When going to the next page, it should start with the first skipped event instead of where the page would normally start.

**Comment by abrahammurciano** [comment]
consider a generator for this maybe? just pull events from the generator as needed, so none will be skipped
