### ISSUE TITLE
/calendar events fails if link in description is over 2000 characters

### ISSUE THREAD

**Issue by abrahammurciano** [DenverCoder1/jct-discord-bot#169]
![image](https://user-images.githubusercontent.com/25041135/115251404-30db1400-a133-11eb-8e83-88a94e461ab9.png)

![image](https://user-images.githubusercontent.com/25041135/115251935-b1017980-a133-11eb-885c-cf27cd045530.png)

if a single event has a description which is too long, and will not be trimmed because the long part is all one link, it makes the message too long anyway and fails to send the message. I don't know if this is worth fixing

**Comment by DenverCoder1** [comment]
Maybe have the embed function trim messages to 2048 characters so it will at least go through?

**Comment by abrahammurciano** [comment]
Do you want to do that whenever? There's a bunch of stuff being appended to different parts of the embed, idk what part are included in the limit
