### ISSUE TITLE
Pig latin is quite buggy

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#17]
More extensive list of consonant digraphs:

`
["bl", "bh", "bw", "br", "cz", "ch", "chr", "cl", "cr", "dh", "dw", "dr", "fl", "fw", "fr", "gh", "gl", "gr", "gn", "kn", "kh", "kl", "kw", "kr", "ll", "lh", "ph", "pl", "pr", "ps", "pw", "qu", "rh", "szch", "sn", "sh", "shr", "shm", "shn", "shl", "shqu", "shw", "sk", "sl", "squ", "sw", "st", "sc", "sch", "scr", "str", "sm", "sp", "sph", "spr", "tch", "ts", "th", "thr", "tw", "tr", "vh", "vh", "vl" "wh", "wr", "xh", "zh"]
`

When the word starts with a vowel, "way" should be appended instead of "ay"

**Comment by abrahammurciano** [comment]
one letter words cause the function to crash

**Comment by abrahammurciano** [comment]
uppercase letters are treated differently to lowercase ones right now

**Comment by DenverCoder1** [comment]
> uppercase letters are treated differently to lowercase ones right now

The underlying issue here is that ["a", "e", "i", "o", "u"] are a special case

**Comment by abrahammurciano** [comment]
https://github.com/geektechdude/Python_Pig_Latin/blob/master/pig_latin_v2.py

**Comment by DenverCoder1** [comment]
> [https://github.com/geektechdude/Python_Pig_Latin/blob/master/pig_latin_v2.py](https://github.com/geektechdude/Python_Pig_Latin/blob/master/pig_latin_v2.py?rgh-link-date=2021-01-07T22%3A38%3A08Z)

No digraphs?

**Comment by abrahammurciano** [comment]
> No digraphs?

I don't even know how pig latin works, i give up with this feature, one of the first years can tackle it for practice. doesn't have to be perfect, its just an example

**Comment by DenverCoder1** [comment]
A better pig latin: https://repl.it/@eyl327/InternalAmpleDominspector-1#main.py

**Comment by abrahammurciano** [comment]
We should just get rid of this easter egg by now...

**Comment by DenverCoder1** [comment]
Pig latin removed in #124
