### ISSUE TITLE
Come up with a creative name for the bot

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#18]
`JCT Bot` is a boring name for a bot.

Discuss here what could make it better.

This issue will be closed with no PR (the name will be changed in the Discord Developer Portal)

**Comment by abrahammurciano** [comment]
`JCTP0`

**Comment by probably-raptors** [comment]
> `JCTP0` - Student-Cyborg Relations

Only if we change all its quotes to polite/indignant protocol droid stuff #

**Comment by abrahammurciano** [comment]
We can use this issue to test the solution to #8 User Polling when that's ready

**Comment by abrahammurciano** [comment]
Jaecey Tee

**Comment by abrahammurciano** [comment]
This was settled by vote. The bot is now called Abbot Engelborg
