### ISSUE TITLE
Command to get information from the Github for developers.

### ISSUE THREAD

**Issue by PSilver22** [DenverCoder1/jct-discord-bot#198]
Since this project is clearly very busy, I think it'd be a good idea to have a command that gives updated information from the Discord about opened issues, pull requests, maybe (if it's possible) a way to see projects assigned to a specific discord account.

**Comment by abrahammurciano** [comment]
GitHub does a good enough job at organising its information, I don't think it's worth implementing this feature. furthermore, if it is implemented, it would only be used by a very small number of people, and it would probably be harder to use it than to learn how to properly use Github.

That said, if you still want to implement this, go right ahead, just don't use slash commands for these, as it's not worth having these extra commands available and visible to everyone who is not gonna use it.

**Comment by PSilver22** [comment]
Sounds good.
