### ISSUE TITLE
Help command to explain how to use the bot

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#24]
The bot can read a list of instructions from a markdown file to display to a user when a `~help` command is triggered.

These markdown docs should be updated every time a feature is added or changed.

**Comment by abrahammurciano** [comment]
I believe there is a default help command, and a way to add documentation to a command in the python file next to each command. Not quite sure how it works yet, would need to look it up

**Comment by DenverCoder1** [comment]
We could replace it with something more user friendly possibly, although not a top priority.
