### ISSUE TITLE
Adding a course

### ISSUE THREAD

**Issue by abrahammurciano** [DenverCoder1/jct-discord-bot#3]
There should be a command to add a course (only usable by admins), the bot should create a channel with the name of the course. No additional setup or permissions are necessary, since everyone can access all the courses.

**Comment by zabrown2000** [comment]
Can @abrahammurciano or @DenverCoder1 please take a look at our current code? We are having trouble when checking to see if a category and/or channel exists. Also, when it comes to the end of the create channel function, the channel isn't being created when the category parameter is put in. There are a lot of underlying issues but mainly we can't figure out the above (create a channel within a category and to see if they exist).
Thanks! (no rush we're working really slowly on this anyway)

**Comment by abrahammurciano** [comment]
Closed by #106
