### ISSUE TITLE
Raised Exceptions are not centrally handled

### ISSUE THREAD

**Issue by benjitusk** [DenverCoder1/jct-discord-bot#369]
The following cases can cause the bot to crash:

- Requesting a comic number that does not exist
- Getting a non-200 response code from the XKCD Heruku search app
- Getting an empty response from the XKCD Heruku search app
- Getting a non-200 response code when fetching the latest comic

**Comment by DenverCoder1** [comment]
I think it used to handle all exceptions, possibly only before the first slash command migration.

When migrating to nextcord, we should be able to catch anything unhandled with an [`on_application_command_error`](https://docs.nextcord.dev/en/latest/api.html#nextcord.Client.on_application_command_error) listener or [`on_error`](https://docs.nextcord.dev/en/latest/api.html#nextcord.on_error) I think.

**Comment by benjitusk** [comment]
So in order to catch all exceptions in one place, I should not deal with them individually, but I should leave them to be handled by nextcord's `on_error` method, which would presumably send a user-friendly ephemeral message. Is that right?

**Comment by DenverCoder1** [comment]
Yeah, if they all are implemented about the same way, it's better to do it in one place.

Note that if the command is already responded to when the error occurs, it can't send another response, only a followup.

[`interaction.send`](https://docs.nextcord.dev/en/latest/api.html#nextcord.Interaction.send) can be used to send a response or followup based on whether one has been sent yet or not.

**Comment by benjitusk** [comment]
Closed by b6b2c99
