### ISSUE TITLE
Command to teach users how to use codeblocks (and other discord tools?)

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#43]
Putting a backslash before the first ` should escape the codeblock for showing an example.

![image](https://user-images.githubusercontent.com/20955511/104655776-ddd26a80-56c6-11eb-8f41-eaafc5476808.png)

Can be invoked with `++codeblock` or similar

**Comment by abrahammurciano** [comment]
Probably about equivalently hard to teach them how to use the bot command than how to use code blocks

**Comment by DenverCoder1** [comment]
It would basically be if someone posts code without a codeblock, someone can call the command so the bot can teach them how.

Now that I think about it, we might even be able to detect code outside a codeblock without having to run a command.

**Comment by DenverCoder1** [comment]
Examples of what I mean:

(from r/webdev server)

![image](https://user-images.githubusercontent.com/20955511/104668754-5e05c980-56e1-11eb-8fb0-72474cb35db0.png)

![image](https://user-images.githubusercontent.com/20955511/104668883-a3c29200-56e1-11eb-8a5a-5ef61d28a8d9.png)

![image](https://user-images.githubusercontent.com/20955511/104668393-aa9cd500-56e0-11eb-9163-8c55b33baeb6.png)

**Comment by abrahammurciano** [comment]
Consider the ability to request specific instructions, like this:
```
++markdown italics
```
or
```
++md code blocks
```
or
```++md codeblock```
