### ISSUE TITLE
++logs doesn't work after restarting because err.log doesn't exist

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#45]
Heroku restarts occasionally (whenever it crashes, gets a new deployment, and every 24 hours). Every time this happens, the files are reset to what appears on GitHub meaning err.log and any local data gets removed.

If `++logs` is called before errors have been logged, it will throw an error:

```
[Errno 2] No such file or directory: 'err.log'
```

### Potential fixes:

1. Check if the file exists before trying to open it
2. Create err.log when it does not exist on startup?
2. Store logs in a place they won't get deleted (ex. a different server)

**Comment by abrahammurciano** [comment]
Just upload an empty err.log to GitHub? Also why do files get deleted?

**Comment by DenverCoder1** [comment]
> Just upload an empty err.log to GitHub?

Having an empty file on GitHub is one of the solutions I thought of but sounds like the wrong solution. Certain things aren't meant to be committed. (`*.log` is part of the default gitignore.)

> Also why do files get deleted?

It part of the way the filesystem works

https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

We should probably look into different options for storing data long-term.

We also don't have to keep it on Heroku if you can find better options. One advantage to this is it's free, though.

**Comment by abrahammurciano** [comment]
So yeah
```py
if file doesn't exist:
    raise FriendlyError("Nothing to report, m'lord", ctx.channel)
```

**Comment by DenverCoder1** [comment]
This is my thought as well
