### ISSUE TITLE
Update welcome message for new roles

### ISSUE THREAD

**Issue by probably-raptors** [DenverCoder1/jct-discord-bot#49]
The instructions to new users does not apply to the new Staff and Professor roles, and should be updated to handle them accordingly.

**Comment by abrahammurciano** [comment]
I thought about this, I specifically think we should keep it as is, so new students dont get funny ideas of pretending to be staff members. In the invitation I sent to teachers, I mentioned that when they join they should tag an admin with @Admin and let us know their name
