### ISSUE TITLE
Ability to lock and unlock voice channels

### ISSUE THREAD

**Issue by abrahammurciano** [DenverCoder1/jct-discord-bot#54]
Anyone in a voice channel should be able to use ++lock (eg in #botspam) to lock the channel to the current participants only (lock emoji can be added to the channel name). If anyone tries to join when it's locked, the bot should disconnect them. Anyone in a locked voice channel should be able to unlock it with ++unlock

**Comment by abrahammurciano** [comment]
Used the same bot as the one that solved #53 for this functionality

**Comment by KABIL19022004** [comment]
have u explain the  how to speak discord locked channal in without permission
