### ISSUE TITLE
Check why this is this way, and what was intended.

### ISSUE THREAD

**Issue by abrahammurciano** [DenverCoder1/jct-discord-bot#70]
/modules/help/help_command.py:35-37
```py
if cog and cog.description:
	description = f"{cog.description}\n{value}"
embed.add_field(name=name, value=value)
```
Remove this assignment to local variable 'description'; the value is never used.

**Comment by DenverCoder1** [comment]
Was supposed to be:

```py
if cog and cog.description:
	value = f"{cog.description}\n{value}"
embed.add_field(name=name, value=value)
```

That way, if we provided cog descriptions (which we don't currently), the description would be displayed above the list of commands.
