### ISSUE TITLE
User Polling

### ISSUE THREAD

**Issue by PSilver22** [DenverCoder1/jct-discord-bot#8]
Whenever someone would like to get a group opinion on something they can give the bot a question and options. The bot can then set up a method to judge how many people vote (ex. message with reactions) for each option and after a set amount of time it says which option won.

**Comment by abrahammurciano** [comment]
> ~poll How much cholent? |  :yum: More | :cry: Less

Consider simplifying the interface by not needing to provide an emoji for each option, and instead using :regional_indicator_a:, :regional_indicator_b:, etc automatically

(or make the emoji optional, i.e. if an emoji is not provided, assign it the next available regional indicator (if you do this, make sure that if the user specified a regional indicator (even not contiguously) to mark it as used and not assign it to any other options))

**Comment by DenverCoder1** [comment]
> after a set amount of time it says which option won.

Keep in mind that the bot might crash or get restarted losing all locally stored data if running on Heroku. So if you want to keep track of when the timers will run out, you might want to use active storage. If necessary, I can set up a basic web API for storing/retrieving data.

**Comment by abrahammurciano** [comment]
> > after a set amount of time it says which option won.
> 
> Keep in mind that the bot might crash or get restarted losing all locally stored data if running on Heroku. So if you want to keep track of when the timers will run out, you might want to use active storage. If necessary, I can set up a basic web API for storing/retrieving data.

To solve this without requiring storage, you can set it up so after the bit crashes, when the bot is ready again, it checks past messages for polls which should be active and continues to keep track of them

**Comment by abrahammurciano** [comment]
It's probably best to add polls to the database. Fields could probably be:
| field name | type | constraints | description |
| --- | --- | --- | --- |
| message | bigint | primary key | the discord ID of the message |
| host_channel | bigint | not null | the dsicord ID of channel which contains the poll (needed to fetch the message object from discord.py) |
| num_options | int | not null | can be used to check if a reaction emoji is valid, eg 🅿️ is invalid if num_options < 16 |

**Comment by abrahammurciano** [comment]
Another feature we might want is to allow people to suggest new options mid-poll. For example, if the poll is:
Q: what should we name the bot?
A: JCT Discord Bot
B: JCTP0
but we may want to allow other people to suggest new options, so they could react to the message with a + emoji, and if they're an allowed editor (would have to be specified at poll creation which roles/users are allowed by tagging them) then the bot might ask them to provide the option to add within X seconds, then the user might reply "Jessie T." as a new option, then the bot would update the poll and add an option
C: Jessie T.

**Comment by abrahammurciano** [comment]
This was "outsourced" to https://github.com/abrahammurciano/paul-bot
